create table store_shipping
(
    shipping_id int not null,
    store_id    int not null
)
    comment '店铺快递公司表' charset = utf8;

INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 84);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 84);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 84);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 84);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 84);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 86);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 86);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 86);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 86);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 86);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 88);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 88);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 88);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 88);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 88);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 98);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 98);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 98);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 98);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 98);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 101);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 101);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 101);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 101);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 101);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 102);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 102);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 102);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 102);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 102);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 105);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 105);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 105);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 105);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 105);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 107);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 110);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 110);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 110);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 110);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 110);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 114);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 114);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 114);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 114);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 114);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 113);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 113);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 113);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 113);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 113);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 120);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 120);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 120);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 120);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 120);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 121);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 121);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 121);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 121);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 121);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (1, 123);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (2, 123);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (3, 123);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (4, 123);
INSERT INTO bb2_seller.store_shipping (shipping_id, store_id) VALUES (5, 123);