create table store_apply
(
    id                      int unsigned auto_increment
        primary key,
    invite_user_id          int(11) unsigned default 0    not null comment '推荐人开店',
    user_id                 int(10)          default 0    not null comment '申请人会员ID',
    contacts_name           varchar(20)                   null comment '联系人姓名',
    contacts_mobile         varchar(20)                   null comment '联系人手机',
    contacts_email          varchar(50)                   null comment '联系人邮箱',
    company_name            varchar(30)                   null comment '公司名称',
    company_type            tinyint(1)       default 1    null comment '公司性质',
    company_website         varchar(50)                   null comment '公司网址',
    company_province        mediumint(8)     default 0    null comment '公司所在省份',
    company_city            mediumint(8)     default 0    null comment '公司所在城市',
    company_district        mediumint(8)     default 0    null comment '公司所在地区',
    company_address         varchar(100)                  null comment '公司详细地址',
    company_telephone       varchar(20)                   null comment '固定电话',
    company_email           varchar(50)                   null comment '电子邮箱',
    company_fax             varchar(30)                   null comment '传真',
    company_zipcode         varchar(20)                   null comment '邮政编码',
    business_licence_number varchar(20)                   null comment '营业执照注册号/统一社会信用代码',
    business_licence_cert   varchar(100)                  null comment '营业执照电子版',
    threeinone              tinyint(1)       default 1    null comment '是否为一证一码商家',
    reg_capital             varchar(10)                   null comment '注册资金',
    legal_person            varchar(20)                   null comment '法人代表',
    legal_identity_cert     varchar(100)                  null comment '法人身份证照片',
    legal_identity          varchar(50)                   null comment '法人身份证号',
    business_date_start     varchar(20)                   null comment '营业执照有效期',
    business_date_end       varchar(20)                   null,
    orgnization_code        varchar(20)                   null comment '组织机构代码',
    orgnization_cert        varchar(100)                  null comment '组织机构代码证',
    attached_tax_number     varchar(30)                   null comment '纳税人识别号',
    tax_rate                tinyint(2)       default 0    null comment '纳税类型税码',
    taxpayer                tinyint(1)       default 1    null comment '纳税人类型',
    taxpayer_cert           varchar(100)                  null comment '一般纳税人资格证书',
    business_scope          text                          null comment '营业执照经营范围',
    store_name              varchar(30)                   null comment '店铺名称',
    seller_name             varchar(30)                   null comment '卖家账号',
    store_type              tinyint(1)       default 0    null comment '店铺性质',
    store_address           varchar(100)                  null,
    store_person_name       varchar(20)                   null comment '店铺负责人姓名',
    store_person_mobile     varchar(20)                   null comment '店铺负责人手机',
    store_person_qq         varchar(20)                   null comment '店铺联系人QQ',
    store_person_email      varchar(50)                   null comment '店铺负责人邮箱',
    store_person_cert       varchar(100)                  null comment '店铺负责人身份证照片',
    store_person_identity   varchar(50)                   null comment '店铺负责人身份证号',
    bank_account_name       varchar(50)                   null comment '结算银行名称',
    bank_account_number     varchar(50)                   null comment '结算银行账号',
    bank_branch_name        varchar(50)                   null comment '开户银行支行名称',
    bank_province           mediumint(8)     default 0    null comment '开户银行支行所在地',
    bank_city               mediumint(8)     default 0    null comment '开户银行支行所在城市',
    main_channel            tinyint(1)       default 0    null comment '近一年主营渠道',
    sales_volume            varchar(255)                  null comment '近一年销售额',
    sku_num                 mediumint(8)     default 1    null comment '可网售商品数量',
    ec_experience           tinyint(1)       default 0    null comment '同类电子商务网站经验',
    avg_price               decimal(10, 2)   default 0.00 null comment '预计平均客单价',
    ware_house              tinyint(1)       default 0    null comment '仓库情况',
    entity_shop             tinyint(1)       default 0    null comment '有无实体店',
    sc_name                 varchar(50)                   null comment '店铺分类名称',
    sc_id                   int(10)                       null comment '店铺分类编号',
    sc_bail                 mediumint(8)     default 0    null comment '店铺分类保证金',
    sg_id                   tinyint(2)       default 0    null comment '店铺等级编号',
    sg_name                 varchar(30)                   null comment '店铺等级名称',
    store_class_ids         text                          null comment '申请分类佣金信息',
    paying_amount           decimal(10, 2)   default 0.00 null comment '付款金额',
    paying_amount_cert      varchar(100)                  null comment '付款凭证',
    apply_state             tinyint(2)       default 0    null comment '店铺申请状态 0未审核，1通过，2拒绝',
    review_msg              varchar(255)                  null comment '管理员审核信息',
    add_time                int              default 0    null comment '提交申请时间',
    apply_type              tinyint(1)       default 0    null comment '申请类型默认0企业1个人'
)
    charset = utf8;

