create table store
(
    store_id                int auto_increment comment '店铺索引id'
        primary key,
    invite_user_id          int(11) unsigned             default 0         not null comment '推荐人开店',
    store_name              varchar(50)                  default ''        not null comment '店铺名称',
    grade_id                int                          default 0         not null comment '店铺等级',
    user_id                 int                          default 0         not null comment '会员id',
    user_name               varchar(50)                  default ''        not null comment '会员名称',
    seller_name             varchar(50)                  default ''        null comment '店主卖家用户名',
    sc_id                   int                          default 0         not null comment '店铺分类',
    company_name            varchar(50)                  default ''        null comment '店铺公司名称',
    province_id             mediumint unsigned           default 0         not null comment '店铺所在省份ID',
    city_id                 mediumint(8)                 default 0         not null comment '店铺所在城市ID',
    district                mediumint unsigned           default 0         not null comment '店铺所在地区ID',
    store_address           varchar(100)                 default ''        not null comment '详细地区',
    longitude               decimal(10, 7)               default 0.0000000 null comment '商家地址经度',
    latitude                decimal(10, 7)               default 0.0000000 null comment '商家地址纬度',
    store_zip               varchar(10)                  default ''        not null comment '邮政编码',
    store_state             tinyint(1)                   default 2         not null comment '店铺状态，0关闭，1开启，2审核中',
    store_close_info        varchar(255)                 default ''        null comment '店铺关闭原因',
    store_sort              int                          default 0         not null comment '店铺排序',
    store_rebate_paytime    varchar(10)                  default ''        not null comment '店铺结算类型',
    store_time              int                                            null comment '开店时间',
    store_end_time          int                          default 0         null comment '店铺有效截止时间',
    store_logo              varchar(255)                 default ''        null comment '店铺logo',
    store_banner            varchar(255)                 default ''        null comment '店铺横幅',
    store_avatar            varchar(150)                 default ''        null comment '店铺头像',
    seo_keywords            varchar(255)                 default ''        null comment '店铺seo关键字',
    seo_description         varchar(255)                 default ''        null comment '店铺seo描述',
    store_aliwangwang       varchar(64)                  default ''        null comment '阿里旺旺',
    store_qq                varchar(50)                  default ''        null comment 'QQ',
    store_phone             varchar(20)                  default ''        null comment '商家电话',
    store_zy                text                                           null comment '主营商品',
    store_domain            varchar(50)                  default ''        null comment '店铺二级域名',
    store_recommend         tinyint(1)                   default 0         not null comment '推荐，0为否，1为是，默认为0',
    store_theme             varchar(50)                  default 'default' not null comment '店铺当前主题',
    store_credit            int(10)                      default 0         not null comment '店铺信用',
    store_desccredit        decimal(3, 2)                default 0.00      not null comment '描述相符度分数',
    store_servicecredit     decimal(3, 2)                default 0.00      not null comment '服务态度分数',
    store_deliverycredit    decimal(3, 2)                default 0.00      not null comment '发货速度分数',
    store_collect           int unsigned                 default 0         not null comment '店铺收藏数量',
    store_slide             text                                           null comment '店铺幻灯片',
    store_slide_url         text                                           null comment '店铺幻灯片链接',
    store_printdesc         varchar(500)                 default ''        null comment '打印订单页面下方说明文字',
    store_sales             int unsigned                 default 0         not null comment '店铺销量',
    store_presales          text                                           not null comment '售前客服',
    store_aftersales        text                                           not null comment '售后客服',
    store_workingtime       varchar(100)                 default ''        null comment '工作时间',
    store_free_price        decimal(10, 2) unsigned      default 0.00      not null comment '超出该金额免运费，大于0才表示该值有效',
    store_warning_storage   int(10)                      default 0         null comment ' 库存预警数',
    store_decoration_switch int unsigned                 default 0         not null comment '店铺装修开关(0-关闭 装修编号-开启)',
    store_decoration_only   tinyint(1) unsigned          default 0         not null comment '开启店铺装修时，仅显示店铺装修(1-是 0-否',
    is_own_shop             tinyint unsigned             default 0         not null comment '是否自营店铺 1是 0否',
    bind_all_gc             tinyint(1)                   default 0         null comment '自营店是否绑定全部分类 0否1是',
    qitian                  tinyint(1)                   default 0         null comment '7天退换',
    certified               tinyint(1)                   default 0         null comment '正品保障',
    returned                tinyint(1)                   default 0         null comment '退货承诺',
    store_free_time         varchar(10)                  default ''        null comment '商家配送时间',
    mb_slide                text                                           null comment '手机店铺 轮播图链接地址',
    mb_slide_url            text                                           null comment '手机版广告链接',
    deliver_region          varchar(50)                  default ''        null comment '店铺默认配送区域',
    cod                     tinyint(1)                   default 0         null comment '货到付款',
    two_hour                tinyint(1)                   default 0         null comment '两小时发货',
    ensure                  tinyint(1)                   default 0         null comment '保证服务开关',
    deposit                 decimal(10, 2)               default 0.00      null comment '保证金额',
    deposit_icon            tinyint(1)                   default 0         null comment '保证金显示开关',
    store_money             decimal(12, 2)               default 0.00      null comment '店铺可用资金',
    pending_money           decimal(12, 2)               default 0.00      null comment '待结算资金',
    deleted                 tinyint(1) unsigned zerofill default 0         not null comment '未删除0，已删除1',
    goods_examine           tinyint(1)                   default 0         null comment '店铺发布商品是否需要审核',
    service_phone           varchar(20)                  default ''        null comment '客户下单, 接收下单提醒短信',
    domain_enable           tinyint(1)                   default 0         not null comment '是否启用二级域名.1:启用;0:关闭',
    store_type              tinyint(2) unsigned          default 0         not null comment '店铺类型。0普通店铺。供应商店',
    default_store           tinyint(1) unsigned          default 0         not null comment '1为默认k一同步平台必须为自营。可以同步给线下店铺',
    store_notice            varchar(255)                 default ''        not null comment '店铺公告',
    transaction_num         int(10)                      default 0         null comment '交易数量'
)
    comment '店铺数据表' charset = utf8;

create index sc_id
    on store (sc_id);

create index store_name
    on store (store_name);

create index store_state
    on store (store_state);

INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (87, 0, '13040580895', 1, 335, '13040580895', '13040580895', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1598594059, 0, '/public/upload/logo/2020/8-28/1598594321060.png', '', '/public/upload/logo/2020/8-28/1598594331110.png', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 1, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (88, 0, '13052417485', 1, 339, '13052417485', '13052417485', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1598608913, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 1);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (89, 0, '13300101011', 1, 341, '13300101011', '13300101011', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1598839136, 0, '/public/upload/logo/2020/9-1/1598922665387.png', '', '/public/upload/logo/2020/9-1/1598922664430.png', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 1, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 3153746.00, 0.00, 0, 0, '', 0, 0, 0, '', 1);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (90, 0, '18603053050', 1, 342, '18603053050', '18603053050', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1598929559, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (91, 0, '18587569585', 1, 343, '18587569585', '18587569585', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1598941014, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (92, 0, '18687269789', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (93, 0, '18687269789', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (94, 0, '18687269789', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 20301.00, 0.00, 0, 0, '', 0, 0, 0, '0', 1);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (95, 0, '18687532589', 1, 345, '18687532589', '18687532589', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1598955005, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (96, 0, '18923817688', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 3327.00, 0.00, 0, 0, '', 0, 0, 0, '0', 10);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (97, 0, '浅安', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 1, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 23636.66, 0.00, 0, 0, '', 0, 0, 0, '0', 15);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (98, 0, '13052859681', 1, 346, '13052859681', '13052859681', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1598955559, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 168972.99, 0.00, 0, 0, '', 0, 0, 0, '', 2);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (99, 0, '18603059551', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 6);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (100, 0, '13066803937', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (101, 0, '13052633526', 1, 347, '13052633526', '13052633526', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1599035919, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 120441.90, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (102, 0, '13052418596', 1, 348, '13052418596', '13052418596', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1599095467, 0, '/public/upload/logo/2020/9-3/1599101271556.png', '', '/public/upload/logo/2020/9-3/1599101272985.png', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 1, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 14645.00, 0.00, 0, 0, '', 0, 0, 0, '', 1);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (103, 0, '18696966969', 1, 349, '18696966969', '18696966969', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1599129716, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (104, 0, '18687529856', 1, 350, '18687529856', '18687529856', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1599181770, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 3);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (105, 0, '13052065235', 1, 351, '13052065235', '13052065235', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1599182514, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 2, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 76134.58, 0.00, 0, 0, '', 0, 0, 0, '', 5);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (106, 0, '18598756586', 1, 352, '18598756586', '18598756586', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1599187117, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (107, 0, '18687268888', 1, 356, '18687268888', '18687268888', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1599543492, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 123.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (108, 0, '18687269789', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 5);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (109, 0, '18603059851', 1, 357, '18603059851', '18603059851', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1599805142, 0, '', '', '', '', '', '', '', '', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.86, 0.00, 0, 0, '', 0, 0, 0, '', 3);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (110, 0, '13052410252', 1, 358, '13052410252', '13052410252', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1600046671, 0, '/public/upload/logo/2020/9-15/1600133351540.png', '', '/public/upload/logo/2020/9-15/1600133365031.png', '', '', '', '', '13052410252', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 1, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 18813.00, 0.00, 0, 0, '', 0, 0, 0, '', 16);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (111, 0, '13058140233', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '13058140233', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 10);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (112, 0, '15015102661', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '15015102661', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 1);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (113, 0, '13056051048', 1, 361, '13056051048', '13056051048', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1600250103, 0, '/public/upload/logo/2020/9-17/1600327604536.png', '', '/public/upload/logo/2020/9-17/1600327606870.png', '', '', '', '', '13056051048', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 3037.97, 0.00, 0, 0, '', 0, 0, 0, '', 9);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (114, 0, '18687253458', 1, 362, '18687253458', '18687253458', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1600250104, 0, '', '', '', '', '', '', '', '18687253458', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 1234.00, 0.00, 0, 0, '', 0, 0, 0, '', 1);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (115, 0, '18687269789', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '18687269789', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 1, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 7);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (116, 0, '18923817688', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '18923817688', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 6);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (117, 0, '13058140233', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '13058140233', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 18);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (118, 0, '18603059551', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '18603059551', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 3);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (119, 0, '18603059852', 1, 368, '18603059852', '18603059852', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1600304210, 0, '', '', '', '', '', '', '', '18603059852', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (120, 0, '13098040987', 1, 369, '13098040987', '13098040987', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1600304509, 0, '/public/upload/logo/2020/9-21/1600651795460.png', '', '/public/upload/logo/2020/9-21/1600651792641.png', '', '', '', '', '13098040987', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 57851.00, 0.00, 0, 0, '', 0, 0, 0, '', 8);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (121, 0, '13089098909', 1, 370, '13089098909', '13089098909', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1600313685, 0, '', '', '', '', '', '', '', '13089098909', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 5557.00, 0.00, 0, 0, '', 0, 0, 0, '', 2);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (122, 0, '15015102661', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '15015102661', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (123, 0, '13052050250', 1, 372, '13052050250', '13052050250', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1600678606, 0, '/public/upload/logo/2020/9-22/1600739242526.png', '', '/public/upload/logo/2020/9-22/1600739244206.png', '', '', '', '', '13052050250', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 1, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 36346.88, 0.00, 0, 0, '', 0, 0, 0, '', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (124, 0, '13066803937', 0, 0, '0', '', 0, '', 0, 0, 0, '0', 0.0000000, 0.0000000, '0', 1, '', 1, '0', null, 0, '', '', '', '', '', '', '', '13066803937', null, '', 0, '0', 0, 0.00, 0.00, 0.00, 1, null, null, '', 0, '0', '0', '', 0.00, 0, 0, 0, 0, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '0', 0);
INSERT INTO bb2_seller.store (store_id, invite_user_id, store_name, grade_id, user_id, user_name, seller_name, sc_id, company_name, province_id, city_id, district, store_address, longitude, latitude, store_zip, store_state, store_close_info, store_sort, store_rebate_paytime, store_time, store_end_time, store_logo, store_banner, store_avatar, seo_keywords, seo_description, store_aliwangwang, store_qq, store_phone, store_zy, store_domain, store_recommend, store_theme, store_credit, store_desccredit, store_servicecredit, store_deliverycredit, store_collect, store_slide, store_slide_url, store_printdesc, store_sales, store_presales, store_aftersales, store_workingtime, store_free_price, store_warning_storage, store_decoration_switch, store_decoration_only, is_own_shop, bind_all_gc, qitian, certified, returned, store_free_time, mb_slide, mb_slide_url, deliver_region, cod, two_hour, ensure, deposit, deposit_icon, store_money, pending_money, deleted, goods_examine, service_phone, domain_enable, store_type, default_store, store_notice, transaction_num) VALUES (125, 0, '13052635240', 1, 374, '13052635240', '13052635240', 0, '', 0, 0, 0, '', 0.0000000, 0.0000000, '', 1, '', 0, '', 1601348576, 0, '', '', '', '', '', '', '', '13052635240', null, '', 0, 'default', 0, 0.00, 0.00, 0.00, 0, null, null, '', 0, '', '', '', 0.00, 0, 0, 0, 1, 0, 0, 0, 0, '', null, null, '', 0, 0, 0, 0.00, 0, 0.00, 0.00, 0, 0, '', 0, 0, 0, '', 0);