create table user
(
    user_id                     mediumint unsigned auto_increment comment '表id'
        primary key,
    email                       varchar(60)             default ''        not null comment '邮件',
    password                    varchar(255)            default ''        not null comment '密码',
    sex                         tinyint(1) unsigned     default 0         not null comment '0 保密 1 男 2 女',
    birthday                    int                     default 0         not null comment '生日',
    user_money                  decimal(10, 2)          default 0.00      not null comment '用户金额',
    frozen_money                decimal(10, 2)          default 0.00      null comment '冻结金额',
    distribut_money             decimal(10, 2)          default 0.00      null comment '累积分佣金额',
    pay_points                  int unsigned            default 0         not null comment '消费积分',
    paypwd                      varchar(128)                              null comment '支付密码',
    reg_time                    int unsigned            default 0         not null comment '注册时间',
    last_login                  int(11) unsigned        default 0         not null comment '最后登录时间',
    last_ip                     varchar(15)             default ''        not null comment '最后登录ip',
    qq                          varchar(20)             default ''        not null comment 'QQ',
    mobile                      varchar(20)             default ''        not null comment '手机号码',
    mobile_validated            tinyint unsigned        default 0         not null comment '是否验证手机',
    head_pic                    varchar(255)            default ''        not null comment '头像',
    bank_name                   varchar(150)                              null comment '银行名称',
    bank_card                   varchar(50)                               null comment '银行账号',
    realname                    varchar(50)                               null comment '用户真实姓名',
    idcard                      varchar(100)                              null comment '身份证号',
    email_validated             tinyint(1) unsigned     default 0         not null comment '是否验证电子邮箱',
    nickname                    varchar(50)             default ''        not null comment '第三方返回昵称',
    level                       tinyint(1)              default 1         null comment '会员等级',
    discount                    decimal(10, 2)          default 1.00      null comment '会员折扣，默认1不享受',
    total_amount                decimal(10, 2)          default 0.00      null comment '消费累计额度',
    is_lock                     tinyint(1)              default 0         null comment '是否被锁定冻结',
    is_distribut                tinyint(1)              default 0         null comment '是否为分销商 0 否 1 是',
    first_leader                int                     default 0         null comment '第一个上级',
    second_leader               int                     default 0         null comment '第二个上级',
    third_leader                int                     default 0         null comment '第三个上级',
    token                       varchar(64)             default ''        null comment '用于app 授权类似于session_id',
    underling_number            int(5)                  default 0         null comment '用户下线数',
    message_mask                bit(6)                  default b'111111' not null comment '消息掩码',
    push_id                     varchar(30)             default ''        not null comment '推送id',
    distribut_level             tinyint(2)              default 0         null comment '分销商等级',
    xcx_qrcode                  varchar(255)                              null comment '小程序专属二维码',
    is_store_member             int(11) unsigned        default 0         not null comment '属于哪个店铺的会员',
    is_entry                    tinyint(1) unsigned     default 0         not null comment '0平常注册，1微信注册绑定，2微信账号关联',
    manifesto                   varchar(255)            default ''        not null comment '个人签名',
    distribut_withdrawals_money decimal(10, 2) unsigned default 0.00      not null comment '累积分销佣金提现'
)
    charset = utf8;

create index email
    on user (email);

create index mobile
    on user (mobile_validated);

INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (361, 'nts243@ntsitech.com', '{bcrypt}$2a$10$vPOb7cBH0uGPpRWFqTN.XezQ3IFeQY17ovKZOuBIJanCeXbWPZYM2', 0, 0, 3037.97, 0.00, 0.00, 0, null, 1600250103, 0, '', '', '13056051048', 0, '', null, null, null, null, 0, '13056051048', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (362, 'nts244@ntsitech.com', '{bcrypt}$2a$10$59mDtma.X22Ykyfi99WgY.HZrL6w5e9uZlPgcrfEfPrpEKKsj71Fa', 0, 0, 1234.00, 0.00, 0.00, 0, null, 1600250104, 0, '', '', '18687253458', 0, '', null, null, null, null, 0, '18687253458', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (363, '', '{bcrypt}$2a$10$dAQyjM63dM1cNOXCMUCCb.A3gnjPV1vgDMahnGufJUfRwVCclrita', 0, 0, 9847203.00, 0.00, 0.00, 0, '{bcrypt}$2a$10$ctYmNvt/t5TovorM8gmWyOgodMgi7JXItjHEvuAjOOxB0y3o/0M7W', 1600250419, 1600848862, '', '', '18687269789', 0, '', null, null, null, null, 0, '18687269789', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 13, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (364, '', '{bcrypt}$2a$10$DEF7vqSo2QXpdWTAH8L4Uel5B2jpllmlGVZYgTzO0Nl8gnIGBTL4K', 0, 0, 9995871.00, 0.00, 0.00, 0, '{bcrypt}$2a$10$QmxLw8QvdMxkNtRXmfUuguTTKZwrIY5hAm6sOG8vMiw3KnLJMIJya', 1600250689, 1600849180, '', '', '13058140233', 0, '', null, null, null, null, 0, '13058140233', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 31, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (365, '', '{bcrypt}$2a$10$d9054MRqJEGj0d0g2KgrDueZZYnlbiTVkbm9oKGUPG6eS.dGCS4.C', 0, 0, 10002230.03, 0.00, 0.00, 0, '{bcrypt}$2a$10$7TKk0bg8NixyIQ3dd6HCzOs/r0N3pYLFqNkUwDuoDOrUrDXTsCm.G', 1600252772, 1601372318, '', '', '18923817688', 0, '/public/upload/head_pic/2020/9-28/1601270620558.jpg', null, null, null, null, 0, '18923817688', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 12, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (366, '', '{bcrypt}$2a$10$MEqfq32KqTsoWGqSVUSE/OhPjeQDr62aFcVw5bidjLdTI7IbNKwWe', 0, 0, 9966122.00, 0.00, 0.00, 0, '{bcrypt}$2a$10$PW6zS6FqcYzrgSt16VWOneWgKLUdOmQ5hQCewtXbyjykbwBPBIIze', 1600256718, 1601371980, '', '', '18603059551', 0, '', null, null, null, null, 0, '18603059551', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 5, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (367, '', '{bcrypt}$2a$10$RQHZt8pTFmJG4RphPK0pAu6WguxdfGqueEj/OpsoODUSdoQ/i.T2K', 0, 0, 0.00, 0.00, 0.00, 0, '{bcrypt}$2a$10$GgkKe9g9d/3FLgPu7l2GnOijWpztr646Kcdhk9zMKGNCzj4fW8PI2', 1600304086, 1600305250, '', '', '15889781738', 0, '', null, null, null, null, 0, '15889781738', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (368, 'nts245@ntsitech.com', '{bcrypt}$2a$10$RdlSwe/PQhSsLffLqkgIFe3TyGQIBshiItKHQa3VbPTidwpL4ovc6', 0, 0, 0.00, 0.00, 0.00, 0, null, 1600304210, 0, '', '', '18603059852', 0, '', null, null, null, null, 0, '18603059852', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (369, 'nts246@ntsitech.com', '{bcrypt}$2a$10$gEiyO.1ra4Pdf/DkXcJdxOpnSxc8nTsBJfWNYYfKIbsHvZGbSMr.W', 0, 0, 57851.00, 0.00, 0.00, 0, null, 1600304509, 0, '', '', '13098040987', 0, '', null, null, null, null, 0, '13098040987', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (370, 'nts247@ntsitech.com', '{bcrypt}$2a$10$lURsIBXiRVf.1eGY4tMiP.XWrypqZnjjL0LzyHQhLDizOQ10zGWsq', 0, 0, 5557.00, 0.00, 0.00, 0, null, 1600313685, 0, '', '', '13089098909', 0, '', null, null, null, null, 0, '13089098909', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (371, '', '{bcrypt}$2a$10$xb/1Es/mi2kjeVpHNGYJQeVUv0jTYMZCYAjSlPRh5z/UAdsNZzQ9C', 0, 0, 9969010.00, 0.00, 0.00, 0, '{bcrypt}$2a$10$8b5II5pnq.F2kmaigQOOLuIeIcrdDJsiz5FhFU93qTnkAU7rpiPOK', 1600397376, 1600910393, '', '', '15015102661', 0, '', null, null, null, null, 0, '15015102661', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 5, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (372, 'nts248@ntsitech.com', '{bcrypt}$2a$10$cnqih6CSpBeimK/dTQF6ied6eZPYYJLfLMZfDjMv6C62Oxp/5AAJm', 0, 0, 65346.88, 0.00, 0.00, 0, null, 1600678606, 0, '', '', '13052050250', 0, '', null, null, null, null, 0, '13052050250', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (373, '', '{bcrypt}$2a$10$y3ICy9jBxiMbbBW59PjXAO8zlRgct/i52cHMTXVXmyn0sq.Jhly0O', 0, 0, 10086534.12, 0.00, 0.00, 0, '{bcrypt}$2a$10$.WdOpHDIbT0qiMQG7aiJceknMUq9a2HBXkZJWDXL0lw8Yn9w0zp9K', 1600739632, 1600742947, '', '', '13066803937', 0, '', null, null, null, null, 0, '13066803937', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 5, b'111111', '', 0, null, 0, 0, '', 0.00);
INSERT INTO bb2_user.user (user_id, email, password, sex, birthday, user_money, frozen_money, distribut_money, pay_points, paypwd, reg_time, last_login, last_ip, qq, mobile, mobile_validated, head_pic, bank_name, bank_card, realname, idcard, email_validated, nickname, level, discount, total_amount, is_lock, is_distribut, first_leader, second_leader, third_leader, token, underling_number, message_mask, push_id, distribut_level, xcx_qrcode, is_store_member, is_entry, manifesto, distribut_withdrawals_money) VALUES (374, 'nts249@ntsitech.com', '{bcrypt}$2a$10$J3BNwk5Hj36hfVlpxhWqZOSqibpMKGRlJaCOsoChldsLsZHjOK8mO', 0, 0, 0.00, 0.00, 0.00, 0, null, 1601348576, 0, '', '', '13052635240', 0, '', null, null, null, null, 0, '13052635240', 1, 1.00, 0.00, 0, 1, 0, 0, 0, '', 0, b'111111', '', 0, null, 0, 0, '', 0.00);