create table config
(
    id       smallint(6) unsigned auto_increment
        primary key,
    name     varchar(50)  null,
    value    varchar(512) null,
    inc_type varchar(20)  null,
    `desc`   varchar(50)  null
)
    charset = utf8;

INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (1, 'express_switch', '0', 'express', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (2, 'kd100_key', 'HNJAfQWU6831', 'express', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (3, 'kdniao_id', '', 'express', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (4, 'kdniao_key', '', 'express', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (5, 'record_no', '粤ICP备15065422号-3', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (6, 'store_name', '新时空数宝商城', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (7, 'company_name', '深圳市新时空智能系统科技有限公司', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (8, 'store_logo', '/public/upload/logo/2020/8-18/1597720322893.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (9, 'store_user_logo', '/public/static/images/logo/pc_home_user_logo_default.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (10, 'store_ico', '/public/upload/logo/2018/03-20/82d37f6770ce7ef6a98c1a9aaf951a3d.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (11, 'store_title', 'TPshop开源商城', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (12, 'store_desc', '国内著名的开源商城系统', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (13, 'store_keyword', '速度 开源  安全 高效', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (14, 'seller_login_logo', '/public/static/images/logo/seller_login_logo_default.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (15, 'admin_login_logo', '/public/static/images/logo/admin_login_logo_default.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (16, 'admin_home_logo', '/public/upload/logo/2020/8-24/1598247391463.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (17, 'wap_home_logo', '/public/static/images/logo/wap_home_logo_default.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (18, 'wap_login_logo', '/public/static/images/logo/wap_logo_default.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (19, 'contact', '张先生', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (20, 'phone', '15889560670', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (21, 'address', '深圳市龙岗区坂田街道城市山海中心', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (22, 'qq', '2852506358', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (23, 'qq2', '2852506359', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (24, 'qq3', '2852506357', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (25, 'point_send_limit', '50', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (26, 'point_min_limit', '200', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (27, 'point_use_percent', '50', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (28, 'auto_confirm_date', '1', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (29, 'auto_transfer_date', '1', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (30, 'auto_service_date', '1', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (31, 'integral_use_enable', '1', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (32, 'reduce', '1', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (33, 'point_rate', '10', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (34, 'complain_time_limit', '30', 'complain', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (35, 'reg_integral', '200', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (36, 'file_size', '1', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (37, 'default_storage', '1', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (38, 'need', '10', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (39, 'min', '10', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (40, 'tax', '12', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (41, 'hot_keywords', '酒 | 艺术品 | 纪念币', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (42, 'is_bind_account', '0', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (43, 'sms_platform', '1', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (44, 'sms_appkey', 'LTAI4GBhGRNt2P111ssig9wJ', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (45, 'sms_secretKey', 'IK6hq1zqQxDmk0F5o9GkhQrbIzKIu4', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (46, 'sms_product', 'NTS通证', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (47, 'regis_sms_enable', '1', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (48, 'forget_pwd_sms_enable', '1', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (49, 'bind_mobile_sms_enable', '1', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (50, 'order_add_sms_enable', '1', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (51, 'order_pay_sms_enable', '1', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (52, 'order_shipping_sms_enable', '1', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (53, 'virtual_goods_sms_enable', '1', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (54, 'sms_time_out', '60', 'sms', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (55, 'sign_on_off', '1', 'sign', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (56, 'sign_integral', '5', 'sign', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (57, 'sign_signcount', '2', 'sign', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (58, 'sign_award', '20', 'sign', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (59, 'is_mark', '1', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (60, 'mark_type', 'text', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (61, 'mark_txt', 'NTS', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (62, 'mark_txt_size', '30', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (63, 'mark_txt_color', '#000000', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (64, 'mark_img', '', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (65, 'mark_width', '', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (66, 'mark_height', '', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (67, 'mark_degree', '54', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (68, 'mark_quality', '50', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (69, 'sel', '5', 'water', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (70, 'switch', '1', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (71, 'distribut_set_by', '0', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (72, 'regrade', '1', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (73, 'first_rate', '4', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (74, 'second_rate', '3', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (75, 'third_rate', '2', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (76, 'qr_back', '/public/upload/weixin/2018/03-07/01ecfdadf99c1b2b01baad0a991bd324.jpg', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (77, 'qr_big_back', '/public/upload/weixin/2018/03-07/f6af99ea507fdb2ba29febcb5fb7e888.jpg', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (78, 'qrcode_menu_word', '我的二维码', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (79, 'qrcode_input_word', '我的二维码', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (80, 'smtp_server', '', 'smtp', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (81, 'smtp_port', '465', 'smtp', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (82, 'smtp_user', '', 'smtp', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (83, 'smtp_pwd', '', 'smtp', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (84, 'regis_smtp_enable', '0', 'smtp', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (85, 'test_eamil', '', 'smtp', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (86, 'team_order_limit_time', '60', 'shopping', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (87, 'site_domain', 'http://kingda.com', 'subdomain', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (88, 'weixin_qrcode', '/public/static/images/qrcode.png', 'shop_info', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (89, 't_number', '687474703a2f2f61706974657374322e747073686f702e636e2f686f6d652f546a2f7032', null, null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (90, 'bd_ak', 'xXo650H9zUKh1Lk19Ztsn984G3Td85', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (91, 'bd_serverak', 'WWeszdz3UyzdtLdmcG4OP0oePjSHSwqh', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (92, 'im_choose', '1', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (93, 'im_website', 'https://im.tpsns.com', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (94, 'ws_socket', 'wss://im.tpsns.com:8283', 'basic', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (95, 'enabled_subdomain', '0', 'subdomain', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (96, 'subdomain_edit', '1', 'subdomain', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (97, 'subdomain_times', '3', 'subdomain', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (98, 'site_domain', 'http://kingda.com', 'subdomain', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (99, 'subdomain_length', '3-12', 'subdomain', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (100, 'open_store_time', '0', 'distribut', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (101, 'cash_open', '1', 'cash', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (102, 'service_ratio', '0', 'cash', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (103, 'min_service_money', '0', 'cash', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (104, 'max_service_money', '0', 'cash', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (105, 'min_cash', '0', 'cash', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (106, 'max_cash', '10000', 'cash', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (107, 'count_cash', '50000', 'cash', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (108, 'cash_times', '5', 'cash', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (109, 'kd100_customer', 'F850ECA122EF25372E21CE7DDC2B514D', 'express', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (110, 'shipping_code', 'shunfeng', 'express', null);
INSERT INTO bb2_mall.config (id, name, value, inc_type, `desc`) VALUES (111, 'shipping_n_code', 'SF', 'express', null);